### PR TITLE
fix(create.ts): remove author tag

### LINKED ISSUE #96: Tag from metadata author
Remove the #0000 (tag/discriminator) from the author name in metadata. (create.ts)

### PR DESCRIPTION
**Pull request by DarkVillager**
Resolves #96 
Before:
image

After:
image

### CODE REVIEW

**Comment by RisingSunLight42** [comment]
Discriminator is not stored in username

**Comment by DarkVillager** [comment]
> Discriminator is not stored in username

check the images.

**Comment by RisingSunLight42** [comment]
> > Discriminator is not stored in username
> 
> check the images.

Tested on the current version of the repo, and there's no discriminator

**Comment by theusaf** [comment]
Proof of current version working:
image
Proof of why it looks like it isn't working in your 'before' image. Basically, `npm list` shows version numbers based on `package.json` and `package-lock.json`, but not the actual version in the dependency's `package.json`.
image

**Pull request closed without merging**
