### PR TITLE
chore: update to add enum & improvements

### PR DESCRIPTION
**Pull request by DarkVillager**
Goes with https://github.com/PreMiD/Presences/pull/7345
Screenshot_25

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
Why single qoutes?

**Comment by DarkVillager** [comment]
> Why single qoutes?

Cuz prettier

**Comment by Bas950** [comment]
> > Why single qoutes?
> 
> Cuz prettier

Doesn't the prettier in the Presences repo use double qoutes?

**Comment by DarkVillager** [comment]
> > > Why single qoutes?
> > 
> > 
> > Cuz prettier
> 
> Doesn't the prettier in the Presences repo use double qoutes?

Let me check

**Pull request merged**
